### PR TITLE
v2.3 - fix: set chain-id to main for main|prod network

### PR DESCRIPTION
**Pull request by jgreat**
### Motivation

Small change in tools/run-fs.sh helper script to fix the chain-id logic when running on `main` or the legacy `prod` networks.

### Test Plan

```
# build fs for main network
tools/build-fs.sh main

# start fs with run-fs.sh helper script with main or prod networks
tools/run-fs.sh prod

OR

tools/run-fs.sh main

# watch for blocks to start downloading
```

### CODE REVIEW

**Review by brucek — CHANGES_REQUESTED** [review]
2 things:

1. is this change also needed in `build-fs.sh` ?
2. Is there a reason to have both a `prod` and a `main` subdir under ~/.mobilecoin ?  I was heading towards only using `main` there to reduce confusion

**Comment by jgreat** [comment]
Let me see if I can straighten that out.

**Review by briancorbin — APPROVED** [review]

**Comment by jgreat** [comment]
I updated the build and run scripts to align some of the logic.  Set net to `main` when using `prod`.

Testing:
```
# Clean up data and run "test" build
rm -rf ${HOME}/.mobilecoin  && rm -rf target && cargo clean && tools/build-fs.sh test
tools/run-fs.sh test

# Clean up data and run "main" build
rm -rf ${HOME}/.mobilecoin  && rm -rf target && cargo clean && tools/build-fs.sh main
tools/run-fs.sh main

# Clean up data and make sure "prod" build uses "main" net.
rm -rf ${HOME}/.mobilecoin  && rm -rf target && cargo clean && tools/build-fs.sh prod
tools/run-fs.sh prod
```

**Review by brucek — APPROVED** [review]
nice, thx 👍

**Pull request merged**
