### PR TITLE
Update github actions to consolidate duplicated code for building

### PR DESCRIPTION
**Pull request by briancorbin**
Consolidating duplicated code
Changing the copied binaries for full-service to mc-full-service
Adjusting the release script to reflect these changes

### CODE REVIEW

**Comment by eranrund** [comment]
I'm looking at https://github.com/mobilecoinofficial/full-service/actions/runs/3207691446 (which is from the last run) and seeing this:
image

Shouldn't there be a mac arm artifact?

**Comment by briancorbin** [comment]
> I'm looking at https://github.com/mobilecoinofficial/full-service/actions/runs/3207691446 (which is from the last run) and seeing this: image
> 
> Shouldn't there be a mac arm artifact?

I'll run again to double check, but yes there should be

**Comment by briancorbin** [comment]
> What happened to the build job? Looks like this is now only testing one configuration?

renamed it to build_and_pre_release

**Comment by eranrund** [comment]
> > What happened to the build job? Looks like this is now only testing one configuration?
> 
> renamed it to build_and_pre_release

I'm only seeing these checks:
image

Previously this had:
image

**Comment by briancorbin** [comment]
weird, idk, but it definitely ran https://github.com/mobilecoinofficial/full-service/actions/runs/3229524670

maybe something up with github?

**Comment by briancorbin** [comment]
I'll just rerun it

**Comment by briancorbin** [comment]
@eranrund checks showed up!

**Review by eranrund — APPROVED** [review]

**Pull request merged**
