### PR TITLE
V2 API Document Fix and Updates

### PR DESCRIPTION
**Pull request by neilz-tt**
### Motivation

This is needed to update document especially for request and response for V2 APIs

### In this PR

Had manually run all V2 APIs. Fix and update param tables, requests, and responses

Screenshot 2023-01-11 at 23 05 38
Screenshot 2023-01-11 at 22 01 02

### Test Plan

< How to run the unit test, e2e test etc. >
< Or what are the actual request/response might look like (like grpcurl) >

### Future Work
* < Out of scope non-goals for this PR >
* < These should be links to tickets. If the tickets do not exist, make them. >

### CODE REVIEW

**Review by briancorbin — CHANGES_REQUESTED** [review]
This looks great, thank you so much! My only request is that this get merged into develop, not main.

**Comment by holtzman** [comment]
> This looks great, thank you so much! My only request is that this get merged into develop, not main.

Oh my! That was an oversight. It was a branch off develop and I forgot to check that on PR creation! Fixed!

**Comment by holtzman** [comment]
> This looks great, thank you so much! My only request is that this get merged into develop, not main.

oops, I thought I was on my own PR and changed this to develop. I realized my mistake and changed it back to main but @neilz-tt, please do make the change to develop that was requested!

This really does look great.

**Comment by zixu-zhao** [comment]
> This looks great, thank you so much! My only request is that this get merged into develop, not main.

Sure, could you switch that? It seems I don't have permissions to switch the target branch after PR got created.

**Comment by neilz-tt** [comment]
> This looks great, thank you so much! My only request is that this get merged into develop, not main.

Sure, just updated

**Comment by neilz-tt** [comment]
close because mess git tree. Will create a new one

**Pull request closed without merging**
