### PR TITLE
Add watcher information to v2 responses that include block information

### PR DESCRIPTION
**Pull request by eranrund**
### Motivation

This information is needed by the new block explorer, and might also be useful for other users who want access to timestamps and block signatures.

### In this PR
Adding an optional syncing of a `WatcherDB` and exposing the data provided by it, when available, via the V2 API

### Test Plan
I tested this manually. Example response looks like this:
```
...
       "watcher_info": {
          "timestamp": "1673991888",
          "timestamp_result_code": "TimestampFound",
          "signatures": [
            {
              "src_url": "https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node1.test.mobilecoin.com/",
              "archive_filename": "00/00/00/00/00/14/e6/000000000014e648.pb",
              "block_signature": {
                "signature": "31e7de448588e62dca608bde40b0e4d63f091385c420ef5734a27307c523b9a13aa9fabe78dd5f3efe9aed790351ed7a063e1e601c944ff626cb8f1e1bfca20f",
                "signer": "93fde5c0ae8941df2b58d9831afe823a8861b8d3e3974af5ba4c75b891d3ac75",
                "signed_at": "1673991888"
              }
            },
            {
              "src_url": "https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node2.test.mobilecoin.com/",
              "archive_filename": "00/00/00/00/00/14/e6/000000000014e648.pb",
              "block_signature": {
                "signature": "5434a4c2ae810a11f43d7a15cfe04c94c34663c02f18597313e892bc4c01ca5f2b606ff9ba835e1b4eb34f49c4db64438ab1232e8a60dbc7048460a1f373bb00",
                "signer": "dcb477362fc975a1d0a86cb8ee9d82963d7b3a3e0abba606f15cd2aae786c288",
                "signed_at": "1673991888"
              }
            }
          ]
        }
      }
...
```

### CODE REVIEW

**Review by briancorbin — COMMENTED** [review]
Is this something we could add tests for?

**Comment by eranrund** [comment]
> Is this something we could add tests for?

I think so, I'll try

**Comment by eranrund** [comment]
@briancorbin added tests

**Review by briancorbin — APPROVED** [review]
This looks great, thanks so much for adding this! Will get this in the next release (eta ~2 weeks), but can get it into a pre-release of 2.3.0 earlier if you'd like to start using it sooner

**Comment by eranrund** [comment]
> This looks great, thanks so much for adding this! Will get this in the next release (eta ~2 weeks), but can get it into a pre-release of 2.3.0 earlier if you'd like to start using it sooner

Thank you! I am not personally using it but @Shramp need it for the block explorer, however they have the hackathon branch to work from so not sure if they need a proper release. Might be nice if we can get it deployed but I'm not sure what our policy is on deploying pre-releases.

**Pull request merged**
