### PR TITLE
Deprecate get_all_* Pattern

### PR DESCRIPTION
**Pull request by david1alvarez**
### Motivation

Currently we have implemented a get_all_* pattern for a number of use cases, and we're looking to limit vendor reliance on this pattern.

### In this PR
- Fixes ticket https://app.asana.com/0/1200175610892874/1201824758436244/f
- Marks get_all_* pattern api endpoints as deprecated in the documentation, and passes an extra `"deprecated": true` field to the api response body in the results field.

### Future Work
Monitor the endpoints to see if they're still seeing high use by integrators.

### CODE REVIEW

**Review by christian-oudard — CHANGES_REQUESTED** [review]
`get_all_accounts` should not be removed. Rejecting this change, until we figure out what to do here.

**Comment by BrianCorbin** [comment]
> `get_all_accounts` should not be removed. Rejecting this change, until we figure out what to do here.
I think all "get_all" endpoints need to have an alternative paging version, at least. I agree with "get_all_accounts" being an exception for now, as this is most likely never going to be an issue.

**Comment by Shramp** [comment]
thanks for taking this on! I don't think we should mark these as deprecated until we provide an alternative for fetching multiple entities (limit/offset).

**Comment by christian-oudard** [comment]
Removing this, and handling it a different way in a new PR.

**Pull request closed without merging**
